#!/usr/bin/env bash

get_dns_info() {
    local domain=$1
    local subdomain=$2
    
    dig "$subdomain.$domain" | awk -v sd="$subdomain" '
        /^;; ANSWER SECTION:/ {
            getline
            print "The subdomain " sd " is a " $4 " record and points to " $5
        }
    '
}

main() {
    domain=$1
    subdomain=$2
    
    if [ -z "$subdomain" ]; then
        for sd in www lb-01 web-01 web-02; do
            get_dns_info "$domain" "$sd"
        done
    else
        get_dns_info "$domain" "$subdomain"
    fi
}

main "$@"
