#!/usr/bin/env bash
# Installs and configures HAProxy load balancer

# Update packages
apt-get update -y

# Install HAProxy
apt-get install haproxy -y

# Configure HAProxy
cat > /etc/haproxy/haproxy.cfg << 'EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 6901-web-01 13.218.25.33:80 check
    server 6901-web-02 54.197.181.3:80 check
EOF

# Enable HAProxy to start on boot
systemctl enable haproxy

# Restart HAProxy
service haproxy restart
