#!/usr/bin/env bash
# Installs and configures HAProxy load balancer

# Update packages
apt-get update -y

# Install HAProxy
apt-get install haproxy -y

# Backup original config
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure HAProxy
cat >> /etc/haproxy/haproxy.cfg << 'EOF'

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 6901-web-01 13.218.25.33:80 check
    server 6901-web-02 54.197.181.3:80 check
EOF

# Enable HAProxy init script
echo "ENABLED=1" > /etc/default/haproxy

# Restart HAProxy
service haproxy restart
