#!/usr/bin/env bash
# Transfers a file from our client to a server

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  # do not attempt transfer if not enough parameters
  exit 0
fi

FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE" "$USER@$IP:~/"

