#!/usr/bin/env bash
# Configures Nginx server with a custom 404 page and redirect

# Update packages
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create the index page
echo "Holberton School" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx with custom 404 page and redirect
cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Test nginx configuration
nginx -t

# Restart nginx
service nginx restart
