#!/usr/bin/env bash
# Configures Nginx server with a custom 404 page

# Update packages
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create the index page
echo "Holberton School" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure redirect for /redirect_me
sed -i '/listen 80 default_server;/a \    location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

# Configure custom 404 page
sed -i '/listen 80 default_server;/a \    error_page 404 /404.html;' /etc/nginx/sites-available/default

# Start nginx
service nginx start
