#!/usr/bin/env bash
# Configures Nginx server with a custom 404 page and redirect

# Update packages
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create the index page
echo "Holberton School" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Add redirect configuration
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Add custom 404 error page configuration
sed -i '/server_name _;/a \\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
